### ISSUE TITLE
Relax PHP version constraint?

### ISSUE THREAD

**Issue by kinglozzer** [satrun77/silverstripe-hasoneselector#1]
Thanks for the module!

`composer.json` currently specifies `"php": ">=7.1"`, but glancing at the source code I can’t spot any reason for this. I spotted this because I was running a different PHP version on CLI 😅

**Comment by satrun77** [comment]
What is the version of php you are suggesting?

**Comment by kinglozzer** [comment]
I’d personally remove it entirely, and only specify it if the version requirements are different to those of `silverstripe/framework` 😄
